### ISSUE TITLE
使用示例和导入到相关软件的能力~

### ISSUE THREAD

**Issue by ZHOUXING1997** [yangtuooc/swi-openapi#16]
插件很棒~

**Comment by yangtuooc** [comment]
@ZHOUXING1997 收到，我尽快编写使用示例文档，感谢支持！

**Comment by yangtuooc** [comment]
@ZHOUXING1997 Hi，很抱歉让你久等了，我来向你同步一下项目最新的情况
- - -
一个不好的消息：

由于本项目与我们团队的有较强的相关性，其中一些功能是针对团队项目的需求开发的，作为开源项目的通用性不够好；因此考虑不在将该项目作为开源项目继续维护。
- - -
一个好消息：

我正在重新起草一个新的开源项目，结合 [Jetbrains IDE Endpoints-Tool-Window](https://www.jetbrains.com/help/idea/endpoints-tool-window.html) 进行扩展实现，这是官方支持的做法，操作界面如下图所示：
<img width="1054" alt="image" src="https://github.com/yangtuooc/swi-openapi/assets/125647696/2d7a207c-0389-4897-abd1-b34b5bee0ff0">
- - -
目前项目正在完善当中，项目地址：https://github.com/yangtuooc/gin-endpoints

**Comment by ZHOUXING1997** [comment]
其实可以开放处理一部分，比如：自动提取接口的出入参，只做这么一个简单的插件~  
总之插件很棒，能解决 code -> doc 过程中很大的痛点！！！

**Comment by yangtuooc** [comment]
> 其实可以开放处理一部分，比如：自动提取接口的出入参，只做这么一个简单的插件~ 总之插件很棒，能解决 code -> doc 过程中很大的痛点！！！

自动提取接口的出入参更像是一个接口能力而非插件
从目前的情况来看不会有太大的需求，后续如果有需要可以考虑单独提取为一个插件


另外，在生成OAS（OpenAPI Specification)文档的时候，是会包含接口的出入参数的

这个插件可以作为一个基础组件，通过接口抽象通用能力：例如获取接口请求出入参数，可以在此基础上扩展其它能力

**Comment by ZHOUXING1997** [comment]
非常nice，期待您的后续更新
